version: "3.3"
services:
  redis:
    container_name: redis 
    image: redis:latest
    deploy:
      replicas: 1
  tango:
    container_name: tango
    ports:
      - '3000:3000'
    build: 
      context: ./Tango
    depends_on:
      - "redis"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Tango/config.py:/opt/TangoService/Tango/config.py
      - ./Tango/volumes:/opt/TangoService/Tango/volumes
    environment:
      - DOCKER_DEPLOYMENT=prod
      - RESTFUL_KEY=REPLACE_ME_SECRET_TANGO_KEY
      - DOCKER_REDIS_HOSTNAME=redis
      # Path to volumes within the Tango container. Does not need to be modified.
      - DOCKER_VOLUME_PATH=/opt/TangoService/Tango/volumes
      # Modify the below to be the path to volumes on your host machine
      - DOCKER_TANGO_HOST_VOLUME_PATH=/home/ec2-user/autolab-docker/Tango/volumes

  autolab:
    container_name: autolab
    depends_on:
      - mysql
      - certbot
    ports:
      - '80:80'
      - '443:443'
    build: ./Autolab

    # Some volume mappings may seem redundant, but we want to make it explicit
    volumes:
      - ./Autolab/db/:/home/app/webapp/db
      - ./Autolab/config/database.yml:/home/app/webapp/config/database.yml
      - ./Autolab/config/initializers/devise.rb:/home/app/webapp/config/initializers/devise.rb
      - ./Autolab/config/environments/production.rb:/home/app/webapp/config/environments/production.rb
      - ./Autolab/config/autogradeConfig.rb:/home/app/webapp/config/autogradeConfig.rb
      - ./Autolab/courses:/home/app/webapp/courses
      - ./Autolab/courseConfig:/home/app/webapp/courseConfig
      - ./Autolab/assessmentConfig:/home/app/webapp/courses/assessmentConfig
      - ./ssl/certbot/conf:/etc/letsencrypt
      - ./ssl/certbot/www:/var/www/certbot

      # Uncomment the below if you are using your own certificate
      # - ./ssl/fullchain.pem:/etc/letsencrypt/live/test.autolab.io/fullchain.pem
      # - ./ssl/privkey.pem:/etc/letsencrypt/live/test.autolab.io/privkey.pem
      # - ./ssl/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem

      # Comment the below out to disable SSL (not recommended)
      - ./nginx/app.conf:/etc/nginx/sites-enabled/webapp.conf

      # Uncomment the below to disable SSL (not recommended)
      # - ./nginx/no-ssl-app.conf:/etc/nginx/sites-enabled/webapp.conf

    environment:
      - DOCKER_SSL=true # set to false for no SSL (not recommended)
      - RESTFUL_HOST=tango
      - RESTFUL_PORT=3000
      - RESTFUL_KEY=REPLACE_ME_SECRET_TANGO_KEY

  mysql:
    container_name: mysql
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_DATABASE=autolab_development
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-db:/var/lib/mysql

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./ssl/certbot/conf:/etc/letsencrypt
      - ./ssl/certbot/www:/var/www/certbot

volumes:
  mysql-db:

